### ISSUE TITLE
[BUG]Data is not contiguous or the position query parameter

### ISSUE THREAD

**Issue by TheGynome** [Azure/azure-sdk-for-net#10237]
**Describe the bug**
After creating file with (DataLakeFileClient) with Create() 
and appending data via (DataLakeFileClient) file.Append(stream, 0)
and file.Flush(streamLength) this error appears

The uploaded data is not contiguous or the position query parameter value is not equal to the length of the file after appending the uploaded data.

After flushing the File first time the Status (getting by file.GetProperties()) of the file is pending and the content length not equals the uploaded length.

**Comment by wantedfast** [comment]
Hi @TheGynome , 
Here is a [sample ](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Files.DataLake/samples/Sample01a_HelloWorld.cs)of using DataLakeServiceClient. 
Sample code snippet:  

```
string fileContent = <Content>; 
File.WriteAllText(<Path>, fileContent); 
StorageSharedKeyCredential sharedKeyCredential = new StorageSharedKeyCredential(<StorageAccountName>,<StorageAccountKey>); 

// Create DataLakeServiceClient using StorageSharedKeyCredentials 
DataLakeServiceClient serviceClient = new DataLakeServiceClient(<StorageAccountBlobUri>, sharedKeyCredential); 

// Create a DataLake Filesystem 
DataLakeFileSystemClient filesystem = serviceClient.GetFileSystemClient(<FileSystemName>); 
filesystem.Create(); 

// Create a file  
DataLakeFileClient file = filesystem.GetFileClient(<FileName>); 
file.Create(); 

// Append data to the DataLake File  
file.Append(File.OpenRead(<Path>), 0); 
file.Flush(fileContent.Length); 
```

Please feel free to reach us with more detailed information if the error still persists by using the sample. 

@jongio

**Comment by TheGynome** [comment]
Hi @wantedfast. 

i have read the sample, but in my case i use the DataLakeServiceClient in a azure function triggered by a incomming service bus message. The service bus messages includes a message body in type of a byte array. 

I take the byte array to create a MemoryStream to call file.Append. i dont create a temporary file to call this function.

**Comment by MaxThom** [comment]
Exact same issue here. Testing with this code and I have the same result as @TheGynome. 

```
string data = "{Purpose: \"Test\", Content: \"None\"}";
MemoryStream ms = new MemoryStream(Encoding.UTF8.GetBytes(data));
await fileClient.AppendAsync(ms, offset: 0);
await fileClient.FlushAsync(position: ms.Length);
```

**Comment by TheGynome** [comment]
@MaxThom 
I have tried the part "After- Working" - Even with an while loop with 10 tries. Some files work with this solution, but some files not.

**Comment by TheGynome** [comment]
Additional here my minified process:

DataLakeServiceClient service = new DataLakeServiceClient(
                   new Uri("https://lakeurl/"),
                   credential);

            DataLakeFileSystemClient filesystemClient = service.GetFileSystemClient("rawdata");

            // Create directory
            DataLakeDirectoryClient directoryClient = filesystemClient.GetDirectoryClient("Directory");

            using (var stream = new System.IO.MemoryStream(byteArray, true))
            {
                Azure.Response<Azure.Storage.Files.DataLake.Models.PathProperties> fileInfo = null;
                DataLakeFileClient file = directoryClient.GetFileClient("DestinationFileName");
                var createResult = file.Create();

                long streamLength = stream.Length;

                    file.Append(stream, 0);
               
                    int tryCounter = 0;

                    while (tryCounter <= flushMaxTryCount) // 10 tries
                    {
                                              
                            if (tryCounter == 0)
                            {
                                file.Flush(streamLength);

                                fileFlushed = true;
                                break;
                            }
                            else
                            {
                                fileInfo = file.GetProperties();
                                file.Flush(fileInfo.Value.ContentLength);

                                fileFlushed = true;
                                break;
                            }
                    }
            }

**Comment by MaxThom** [comment]
This is my entire code, I dont like the sdk so much as of right now. Lack of documentation and I have no idea how to check if a file exist or not in a proper way.

```c#
            DataLakeFileClient fileClient = null;
            Response<PathProperties> props = null;
            try
            {
                StorageSharedKeyCredential sharedKeyCredential = new StorageSharedKeyCredential(accountName, accountKey);
                var dataLakeServiceClient = new DataLakeServiceClient(new Uri(dfsUri), sharedKeyCredential);
                fileClient = GetBlobFile(dataLakeServiceClient);
                props = await fileClient.GetPropertiesAsync();
            }
            catch (Exception e)
            {
                fileClient.Create();
                props = await fileClient.GetPropertiesAsync();
            }

            string data = "{Purpose: \"Test\", Content: \"None\"}\n";
            MemoryStream ms = new MemoryStream(Encoding.UTF8.GetBytes(data));

            Console.WriteLine($"Data length = {data.Length},  BeforeBlobLength = {props.Value.ContentLength}");

            await fileClient.AppendAsync(ms, offset: props.Value.ContentLength);
            await fileClient.FlushAsync(position: ms.Length + props.Value.ContentLength);

            Console.WriteLine($"Data length = {data.Length},  AfterBlobLength = {ms.Length + props.Value.ContentLength}");
```

For append and flush :
 - Append : you set the cursor in the file from where to append. If you want to append at the end, set the offset at fileInfo.Value.ContentLength
 - Cursor : you flush the steam so it is written to the file. You set the cursor after your newly appended data. Therefore, we get ms.Length + props.Value.ContentLength.

Using your code, can you try something like this ? I dont get why youre doing multiple try.

```c#
       DataLakeFileSystemClient filesystemClient = service.GetFileSystemClient("rawdata");

        // Create directory
        DataLakeDirectoryClient directoryClient = filesystemClient.GetDirectoryClient("Directory");

        using (var stream = new System.IO.MemoryStream(byteArray, true))
        {
            Azure.Response<Azure.Storage.Files.DataLake.Models.PathProperties> fileInfo = null;
            DataLakeFileClient file = directoryClient.GetFileClient("DestinationFileName");
            var createResult = file.Create();
            var fileInfo = file.GetProperties();

            long streamLength = stream.Length;

                file.Append(stream, fileInfo.Value.ContentLength);
                file.Flush(streamLength+fileInfo.Value.ContentLength);
        }
```

**Comment by TheGynome** [comment]
I tried to flush the file multiple times, because the file can be flushed with the second or third try. I do not why?!

But some files could not be flushed. In my case about 500 of multiple million files could not by flushed after 10 tries.

The function i build has about 50 / 60 calls per second.

**Comment by tg-msft** [comment]
Have you seen anything like this @seanmcc-msft?

**Comment by seanmcc-msft** [comment]
Hi everyone,

A couple of clarifications.
- If you call Create() on a file that already exists, the file will be overwritten, and any existing data will be deleted.
- To see if a file already exists, create a new FileClient for its URL, and call GetProperties().  The call will fail with a 404 if the file doesn't exist.  In the next release, we are adding an Exists() method to FileSystemClient, DirectoryClient, and FileClient.
- My understanding is that you can only append to the end of a file.  Appending in the middle of a file that already has data will result in an error.  This is why @MaxThom 's working sample functions correctly.
- Also note that Append() is limited to ~100MB per append.  In the next release, we are adding an Upload() API that will handling Appends and Flushes for the user, as long as you are uploading an entire file.

-Sean

**Comment by TheGynome** [comment]
Hi,

@seanmcc-msft 

to your point:

-  Every file name is an unique filename given by the actual datetime including the milliseconds and the given servicebusmessage id

- See point 1

- I only append the whole file content starting at position 0

- The files i upload are about 10 KB and max 30 KB


So all this given answers do not resolve my problem

**Comment by MaxThom** [comment]
hummm, I feel that one file for every message is a too small granularity. 
Have you tried to create one file per minute and append all new messages in the same minute to that file ? I think i've read they recommended at least 100mb per file.

In my scenario, we have millions of datapoint from sensors coming in every hour, I was thinking of making one hour file per sensorId, and appending new data if they are in the same hour. I will adjust the time range of files upon testing, but thats the overall idea.

**Comment by TheGynome** [comment]
I also tried your proposal @MaxThom.

Hope there will be a fix.

**Comment by pascalnaber** [comment]
Any update on this bug? 
We would like a reliable way of appending to a file

**Comment by gandhirajan** [comment]
@TheGynome  Hi, We faced the exact same issue and the issue was with the file names. It so happened that during our performance runs files are created with same names even when we prefixed milliseconds to the filename resulted in this error. We have corrected this issue now to generate unique filenames using UUID and the issue does not occur anymore. You can also try appending UUID to the filename instead of milliseconds and check once.

This is the issue I reported - https://github.com/Azure/azure-sdk-for-java/issues/10318

**Comment by adamkjonesmesh** [comment]
@MaxThom 's response above solved my problem.  I am using the .NET SDK and was having the same issue as others here.  After implementing @MaxThom 's code, I am able to append files in datalake gen2 storage now in Azure.  Thank you.

**Comment by dieterhowest** [comment]
Hello

This is still a problem, we have a IoT hub and a IoT Hub trigger in Azure Functions. Messages are coming in really fast.
We want to append the messages to a file in Azure Data Lake. But this crashes almost immediately when i call FlushAsync

                string fileName = $"{DateTime.Now.Year}{DateTime.Now.Month}{DateTime.Now.Day}";
                DataLakeFileClient fileClient = directory.GetFileClient(fileName);
                await fileClient.CreateIfNotExistsAsync();
                var fileProperties = await fileClient.GetPropertiesAsync();
                var currentFileLength = fileProperties.Value.ContentLength; // Won't be 0 if the file already exists.
                var result = await fileClient.AppendAsync(ms, offset: currentFileLength);
                var response = await fileClient.FlushAsync(position: currentFileLength + ms.Length);

The error is 
_**The uploaded data is not contiguous or the position query parameter value is not equal to the length of the file after appending the uploaded data**_

I can't get this to work with the workaround above. Is there an other way to process message and append them to a datalake file? I can't believe that Azure Data lake has a problem with really fast appending to files.


regards
Dieter

**Comment by samuelramos** [comment]
> Exact same issue here. Testing with this code and I have the same result as @TheGynome. If I run it then change the data and run it again, I get the error. I figured it out by moving the offset using the file content length as follow :
> 
> BEFORE - NOT WORKING
> 
> ```cs
> string data = "{Purpose: \"Test\", Content: \"None\"}";
> MemoryStream ms = new MemoryStream(Encoding.UTF8.GetBytes(data));
> await fileClient.AppendAsync(ms, offset: 0);
> await fileClient.FlushAsync(position: ms.Length);
> ```
> 
> AFTER - WORKING
> 
> ```cs
>             string data = "\n{Purpose: \"Test4\", Content: \"None\"}";
>             MemoryStream ms = new MemoryStream(Encoding.UTF8.GetBytes(data));
> 
>             var blobProperties = fileClient.GetProperties();
>             Console.WriteLine($"Data length = {data.Length},  BeforeBlobLength = {blobProperties.Value.ContentLength}");
> 
>             await fileClient.AppendAsync(ms, offset: blobProperties.Value.ContentLength);
>             await fileClient.FlushAsync(position: ms.Length + blobProperties.Value.ContentLength);
> 
>             blobProperties = fileClient.GetProperties();
>             Console.WriteLine($"Data length = {data.Length},  AfterBlobLength = {blobProperties.Value.ContentLength}");
> ```
> 
> Hope it help you out !

That just worked for me! Just ensure that the 'data' variable content isn't null or an empty string ("").

**Comment by FrankVDL2471** [comment]
> Hi everyone,
> 
> A couple of clarifications.
> 
> * If you call Create() on a file that already exists, the file will be overwritten, and any existing data will be deleted.
> * To see if a file already exists, create a new FileClient for its URL, and call GetProperties().  The call will fail with a 404 if the file doesn't exist.  In the next release, we are adding Exists() and CreateIfNotExists() methods to FileSystemClient, DirectoryClient, and FileClient.
> * My understanding is that you can only append to the end of a file.  Appending in the middle of a file that already has data will result in an error.  This is why @MaxThom 's working sample functions correctly.
> * Also note that Append() is limited to ~100MB per append.  In the next release, we are adding an Upload() API that will handling Appends and Flushes for the user, as long as you are uploading an entire file.
> 
> -Sean

I'm using the UploadAsync method from the Azure.Storage.Files.DataLake v12.7.0 package , but still the same error is appearing.
Any progress on fixing this issue ?

**Comment by twsl** [comment]
I'm facing the same issue.  Works for a while and then suddenly occurs.
