### ISSUE TITLE
[BUG][Storage][DataLake] DataLakePathClient fails Rename with a NullReferenceException

### ISSUE THREAD

**Issue by davidOSUL** [Azure/azure-sdk-for-net#12991]
**Describe the bug**
Using the DataLakePathClient's Rename or RenameAsync method fails with a System.NullReferenceException

**Expected behavior**
The rename operation successfully renames the file

**Actual behavior (include Exception or Stack Trace)**
a System.NullReferenceException. Stack trace leading up that:
```
DataLakeUriBuilder.set_DirectoryOrFilePath(String value)

    DataLakePathClient.RenameInternal(String destinationPath, String destinationFileSystem, DataLakeRequestConditions sourceConditions, DataLakeRequestConditions destinationConditions, Boolean async, CancellationToken cancellationToken)

    TaskExtensions.EnsureCompleted[T](Task`1 task)

    DataLakePathClient.Rename(String destinationPath, String destinationFileSystem, DataLakeRequestConditions sourceConditions, DataLakeRequestConditions destinationConditions, CancellationToken cancellationToken)
```

**To Reproduce**
Using the code below, assuming this.fileSystemClient is defined as a valid FileSystemClient, change UsePathClient to true.
```c#
[TestMethod]
        public void RenameTest()
        {
            // Setting this to true causes a System.NullReferenceException
            const bool UsePathClient = false;
 
            string oldPath = "oldFileName";
            string newPath = "newFileName";
 
            DataLakePathClient pathClient = new DataLakePathClient(this.fileSystemClient, oldPath);
            DataLakeFileClient fileClient = this.fileSystemClient.GetFileClient(oldPath);
            fileClient.Create();
 
            if (UsePathClient)
            {
                pathClient.Rename(newPath); // failure occurs here
            }
            else
            {
                fileClient.Rename(newPath);
            }
 
            Assert.IsFalse(fileClient.Exists());
            Assert.IsTrue(this.fileSystemClient.GetFileClient(newPath).Exists());
        }

```

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Files.DataLake 12.2.2
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET Core 3.1.301
 - IDE and version : Visual Studio 2019 16.6

**Comment by zsybupt** [comment]
does this has been fixed?

**Comment by AlexGhiondea** [comment]
@davidOSUL @zsybupt there have been several versions released since you filed the bug. Are you able to check if the issue still happens on the latest version?

**Comment by zsybupt** [comment]
@SaurabhSharma-MSFT  We use a workaround, and do not use this approach now

**Comment by trevonmckay** [comment]
I can confirm this issue still exists in Azure.Storage.Files.DataLake 12.11.0

**Comment by trevonmckay** [comment]
reopen
