### ISSUE TITLE
[BUG][FormRecognizer]Items not included in Fields of RecognizedForm for Invoices

### ISSUE THREAD

**Issue by vldmr-bus** [Azure/azure-sdk-for-net#20000]
Results from StartRecognizeInvoicesAsync does not include "Items" field in resulting recognized form, while results for the same document processed through online interface (https://fott-preview.azurewebsites.net/prebuilts-analyze) do include line items as expected. Tested with 3.1.0-beta.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by maririos** [comment]
Thanks for the feedback @vldmr-bus . `3.1.0-beta-3` of the Azure.AI.FormRecognizer SDK targets service version `2.1-preview.2` which didn't expose `Items` under invoices. 
We are currently working on updating the SDK to target the new service version `2.1-preview.3` which includes this. 
I created issue https://github.com/Azure/azure-sdk-for-net/issues/20009 so we can update our samples too

**Comment by maririos** [comment]
FYI @vldmr-bus samples have been added. You can see the update here: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/samples/Sample10_RecognizeInvoices.md
We are going to release version `3.1.0-beta.4` early next week so you can consume it

**Comment by maririos** [comment]
Hey @vldmr-bus we've released the `3.1.0-beta.4` package today which includes all information for Invoices plus new updates the service introduced in version `preview.3`.
You can find it on [NuGet](https://www.nuget.org/packages/Azure.AI.FormRecognizer/3.1.0-beta.4).

Give it a try and let us know if you have any feedback on it :)

**Comment by vldmr-bus** [comment]
Thank you for quick update. I've tested new version and have the following observations:

- The items are now present in invoice.
- All items are missing Quantity and Unit fields that are present in recognized results from online interface (https://fott-preview.azurewebsites.net/prebuilts-analyze)
- When accessing Tax value through Value.AsFloat() an exception is thrown:
```Exception has occurred: CLR/System.InvalidOperationException
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll: 'Nullable object must have a value.'
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_NoValue()
   at System.Nullable`1.get_Value()
   at Azure.AI.FormRecognizer.Models.FieldValue.AsFloat()
```

**Comment by vldmr-bus** [comment]
I noticed that although the result of the invoice recognition is a collection, the example just use a Single() selector, as opposed to receipts recognition example. I tried submitting documents with multiple invoices in content, but the result contained a single invoice regardless. The online interface also did not recognize multiple invoices in the document. So is this a planned limitation, or can we expect it to be lifted in upcoming releases?

**Comment by maririos** [comment]
>All items are missing Quantity and Unit fields that are present in recognized results

You mean in the samples? or when using the feature you never get `Quantity` or `Unit` fields.

> Tax `Value.AsFloat` exception

I was able to repro it. Issue https://github.com/Azure/azure-sdk-for-net/issues/20014 to address it. Thank you so much @vldmr-bus  for reporting it!

> multiple invoices

@kinelski could you provide information here as I recall you looked into this when writing our tests?

**Comment by kinelski** [comment]
>I noticed that although the result of the invoice recognition is a collection, the example just use a Single() selector, as opposed to receipts recognition example. I tried submitting documents with multiple invoices in content, but the result contained a single invoice regardless. The online interface also did not recognize multiple invoices in the document. So is this a planned limitation, or can we expect it to be lifted in upcoming releases?

Currently the Recognize Invoices operation always returns a single invoice. This is a service-side limitation. There are plans to improve the document splitting technology being used, but we still don't have a clear picture of when the change will take place.

For the time being, every invoice to be recognized needs a separate service call. This can be accomplished with the help of the `Pages` property in `RecognizeInvoiceOptions` to specify which pages to recognize in each call. For instance:

```cs
operation = await client.StartRecognizeInvoicesAsync(stream, new RecognizeInvoicesOptions() { Pages = { "1" } });
```

**Comment by vldmr-bus** [comment]
> > All items are missing Quantity and Unit fields that are present in recognized results
> 
> You mean in the samples? or when using the feature you never get `Quantity` or `Unit` fields.

I never get these fields in my tests using sdk, while these fields are present in online recognizer results for the same documents

**Comment by vldmr-bus** [comment]
> For the time being, every invoice to be recognized needs a separate service call. This can be accomplished with the help of the `Pages` property in `RecognizeInvoiceOptions` to specify which pages to recognize in each call. 
Well, our planned solution is completely unattended, it does not have any user interface, so human role in recognition is not an option, unfortunately

**Comment by maririos** [comment]
>I never get these fields in my tests using sdk, while these fields are present in online recognizer results for the same documents

Could you share the SDK code you are writing to get the fields?
Also, any chance you could share a sample or an invoice document you are using (without any PII information) so we can try it in our end?

**Comment by vldmr-bus** [comment]
> Also, any chance you could share a sample or an invoice document you are using (without any PII information) so we can try it in our end?

I had this problem with any invoice, for example, with [this sample from tutorials](https://docs.microsoft.com/en-us/azure/cognitive-services/form-recognizer/media/sample-invoice.jpg): 

> Could you share the SDK code you are writing to get the fields?

Once I re-examined my code for sharing with you, I found the reasons of these two fields missing. The problem was at converting the field to strongly typed object, and they were different for each.

The "Quantity" I expected to come as integer value, but using debugger, I found it to have ValueType "Float", so I can correct that.

The problem with "Unit" is different. Its ValueType comes out as "Float" as well (I expected "String", float kinda makes no sense here), but accessing it as with either type throws an exception -- see debugger session below (itemsField variable here contains the items from the invoice). So it is not clear, how to access this field. Please advise
```
itemsField.Value.ValueType
> List
itemsField.Value.AsList()[0].Value.ValueType
> Dictionary
itemsField.Value.AsList()[0].Value.AsDictionary()["Unit"].Value.ValueType
> Float
itemsField.Value.AsList()[0].Value.AsDictionary()["Unit"].Value.AsFloat()
> 'itemsField.Value.AsList()[0].Value.AsDictionary()["Unit"].Value.AsFloat()' threw an exception of type System.InvalidOperationException'
itemsField.Value.AsList()[0].Value.AsDictionary()["Unit"].Value.AsString()
> 'itemsField.Value.AsList()[0].Value.AsDictionary()["Unit"].Value.AsString()' threw an exception of type System.InvalidOperationException'
```

**Comment by maririos** [comment]
Great. So to confirm the issue you are having now is with `Unit` field with the exception you are sharing right?
We noticed that too and reported it to the service. The fix will come in the next service deployment (end of May) see issue https://prepmod.doh.wa.gov/

**Comment by vldmr-bus** [comment]
> Great. So to confirm the issue you are having now is with `Unit` field with the exception you are sharing right?

That is correct

**Comment by maririos** [comment]
I am sorry for the problem this bug might cause you, and thanks for reporting it.
I would advise to close this issue and follow https://github.com/Azure/azure-sdk-for-net/issues/20015 for when the fix is deployed and available to be consumed

**Comment by vldmr-bus** [comment]
Closing as original issue is resolved. Will follow up on #20014 and #20015
