### ISSUE TITLE
Storage: Review the release strategy and consider minor releases for the critical issues.

### ISSUE THREAD

**Issue by yahorsi** [Azure/azure-sdk-for-net#21638]
Guys, please review the release strategy. It's been more than 3 months since this (https://github.com/Azure/azure-sdk-for-net/issues/18884) issue was reported and there is still no official release that is fixing it. We only have beta4 (https://www.nuget.org/packages/Azure.Storage.Blobs/12.9.0-beta.4) that we can't use cause it's officialy beta and we don't know what else is broken. And to remind how serious the issue is - it is causing ** random data corruption** for the streams opened with **BlockBlobClient.OpenWrite**.

We're paying a huge amount of money for the Azure and such delays are just not acceptable.
Please consider having minor releases for the really critical issues.

**Comment by yahorsi** [comment]
@jsquire I think the title can remain original. This is related to all Azure SDK NuGet packages, not only storage.

**Comment by jsquire** [comment]
Hi @yahorsi.  The clients for each Azure service are managed independently with respect to release schedules and the decision of when a critical issue requires a hotfix.  While I understand the concern that you're raising,  this issue is focused on storage and we'll want to be sure that the right folks to assist are alerted to take ownership.

**Comment by yahorsi** [comment]
@jsquire Thank you

**Comment by amnguye** [comment]
For this bug, we did make a hotfix release for this back on April 27th in Azure.Storage.Blobs 12.8.3
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/CHANGELOG.md#1283-2021-04-27

Which raises another issue if you're currently depending 12.9.0-beta.4 (which contains the same fixes as 12.8.3) are you still experiencing this issue?

**Comment by yahorsi** [comment]
@amnguye Thank you, we were just unaware this is fixed. The original issue was never updated with the release it was fixed in.

**Comment by yahorsi** [comment]
I have explicitly asked for an update when it will be fixed:

![image](https://user-images.githubusercontent.com/9819679/121057876-6c579d80-c7c8-11eb-82b6-806a76a9311f.png)

**Comment by amnguye** [comment]
Apologies for not replying on a closed thread. We will look to better our notification system when issues are closed and there are replies. As a current mitigation, opening a new issue or reopening the issue would let us know that the issue is not resolved yet. For clarification our current process we close issues when they have been resolved in the main branch.

Are you suggesting that for every single release, every customer and issue that is resolved by respective release, is reupdated with the release that resolves it instead of having a change log and release notes?

**Comment by yahorsi** [comment]
@amnguye Yes updating issues sounds logical for me because we are, customers, do not receive any notification when a new release is published so there is no other way other than a refreshing page every day and then looking into the release note to check if my particular issue was fixed in this release or no.

**Comment by amnguye** [comment]
Thanks for your input. We will look to bettering this in the future. I will close the issue now if there are no further actionable items to act on. Please reopen or open a new issue (if unrelated) if needed.
