### ISSUE TITLE
Personalizer Client Library for .NET page doesn't have the correct links 

### ISSUE THREAD

**Issue by achandmsft** [Azure/azure-sdk-for-net#27848]
Can someone please refresh/update the doc ([Azure Personalizer client library ](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/AI.Personalizer-readme-pre) ) to point to the latest NuGet package ([Azure.AI.Personalizer 2.0.0-beta.2](https://www.nuget.org/packages/Azure.AI.Personalizer/2.0.0-beta.2)) in the [install ](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/AI.Personalizer-readme-pre#install-the-package)and [key concepts](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/AI.Personalizer-readme-pre#key-concepts) sections of this doc? Current links/wording in these sections are confusing/outdated with this release.

**Install section:** 
Current: dotnet add package Azure.AI.Personalizer --version 2.0.0-beta.1  
Desired ( @Mohit-Chakraborty to confirm) : dotnet add package Azure.AI.Personalizer --version 2.0.0-beta.2

**Key concepts section:** add link to the nuget package page
Current: Azure.AI.Personalizer is built on top of ...
Desired ( @Mohit-Chakraborty to confirm) : [Azure.AI.Personalizer](https://www.nuget.org/packages/Azure.AI.Personalizer/2.0.0-beta.2) is build on top of ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b04f689b-ba64-a2b5-400b-b9bc935c014f
* Version Independent ID: f9dd7c84-caad-ae65-d7a4-2919d56ecba1
* Content: [Azure Personalizer client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/AI.Personalizer-readme-pre)
* Content Source: [api/overview/azure/ai.personalizer-readme-pre.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/ai.personalizer-readme-pre.md)
* Service: **personalizer**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @orenmichaely
* Microsoft Alias: **ormichae**

**Comment by achandmsft** [comment]
**Install section:** 
Current: dotnet add package Azure.AI.Personalizer --version 2.0.0-beta.1  
Desired ( @Mohit-Chakraborty to confirm) : dotnet add package Azure.AI.Personalizer --version 2.0.0-beta.2

**Key concepts section:** add link to the nuget package page
Current: Azure.AI.Personalizer is built on top of ...
Desired ( @Mohit-Chakraborty to confirm) : [Azure.AI.Personalizer](https://www.nuget.org/packages/Azure.AI.Personalizer/2.0.0-beta.2) is build on top of ...

**Comment by jsquire** [comment]
> Sidebar: Why is the bot adding Azure.Identity to this. This is an AI SDK not an Identity one

The bot makes that determination based on an ML model trained against repository issues; in this case, it had enough confidence to believe Identity was the correct label.   It was obviously mistaken for this one.

**Comment by jsquire** [comment]
We should update to `dotnet add package Azure.AI.Personalizer --prerelease` rather than including a specific version.

**Comment by Mohit-Chakraborty** [comment]
This is the backing GitHub page - https://github.com/Azure/azure-docs-sdk-dotnet/blob/main/api/overview/azure/ai.personalizer-readme-pre.md

**Comment by jsquire** [comment]
That page is generated from the README in the SDK repository.   The source for that is [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/personalizer/README.md).

**Comment by Mohit-Chakraborty** [comment]
Ah, thanks for the info Jesse.

**Comment by achandmsft** [comment]
@johnhuang01 more info in this comments thread around the source to change FYI. Please feel free to add any other comments/questions here.

**Comment by johnhuang01** [comment]
@achandmsft I have sent the PR: https://github.com/Azure/azure-docs-sdk-dotnet/pull/2156

**Comment by Mohit-Chakraborty** [comment]
@jsquire, I don't see an update to the docs page even though we have updated the README in the SDK. I *guess* changes are only picked up upon release.
If we want to force an update, I wonder if it is okay to update the page in `azure-docs-sdk-dotnet` directly.

**Comment by jsquire** [comment]
They're picked up on release and at scheduled intervals.    @danieljurek would be the person to ask about the specifics.

**Comment by danieljurek** [comment]
@johnhuang01 -- please merge the PR if you're ready for the change to go out: https://github.com/Azure/azure-docs-sdk-dotnet/pull/2156

@Mohit-Chakraborty -- These pages update by two means: 
* Updates to the page in the `azure-docs-sdk-dotnet` repo which are later pushed live (on Wednesday, most weeks) 
* Package releases from our CI system which pick up the README.md file from `azure-sdk-for-net` repo for the package, add some metadata, and update the `azure-docs-sdk-dotnet` repo with those changes. 

A new release will pave completely over whatever changes have been made to the markdown file in `azure-docs-sdk-dotnet` since the last release so make sure whatever content is in the `azure-docs-sdk-dotnet` repo is also reflected in your README.md in `azure-sdk-for-net` source repo if you intend to keep it in the next release.

**Comment by Mohit-Chakraborty** [comment]
Understood. Thanks for the info @danieljurek.

**Comment by pallavit** [comment]
@danieljurek I still don't see the personalizer documentation under - https://learn.microsoft.com/en-us/dotnet/api/overview/azure/?view=azure-dotnet-preview.

The PR that had the doc changes were merged https://github.com/Azure/azure-docs-sdk-dotnet/pull/2156. Am I looking at the wrong place?

**Comment by danieljurek** [comment]
@pallavit -- The documentation is live here: https://learn.microsoft.com/en-us/dotnet/api/overview/azure/ai.personalizer-readme?view=azure-dotnet-preview ... It has the changes merged from the PR https://github.com/Azure/azure-docs-sdk-dotnet/pull/2156 

The [top-level ToC to which you link](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/?view=azure-dotnet-preview) is a list of services, not packages. In the case of the `Azure.AI.Personalizer` package the [package lives under the "Cognitive Services" service](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/ai.personalizer-readme?view=azure-dotnet-preview). If the ToC needs to change then the value of `ServiceName` should be updated in the metadata: https://github.com/Azure/azure-sdk/blob/main/_data/releases/latest/dotnet-packages.csv#L63

I'm closing this issue as the concerns have been addressed.
