### ISSUE TITLE
[QUERY] System.ObjectDisposedException When using Azure.WebJobs QueueTrigger

### ISSUE THREAD

**Issue by ruoruyan** [Azure/azure-sdk-for-net#38422]
### Library name and version

Azure.Messaging.ServiceBus:7.16.1.0

### Query/Question

We are using .Net 6.0, azure WebJobs QueueTrigger to consume the service bus.

Here is our service bus config:
```
builder.ConfigureWebJobs(b =>
 {
     b.AddAzureStorageCoreServices();
     b.AddAzureStorageQueues(a =>
     {
         a.BatchSize = 1;
         a.NewBatchThreshold = 1;
         a.MaxDequeueCount = 3;
         a.MaxPollingInterval = TimeSpan.FromSeconds(10);
         a.VisibilityTimeout = TimeSpan.FromSeconds(5);
     });
     b.AddServiceBus(sc =>
     {
         sc.PrefetchCount = 0;
         sc.AutoCompleteMessages = false;
         sc.MaxAutoLockRenewalDuration = maxAutoLockRenewalDuration;
         sc.MaxConcurrentSessions = 1;
         sc.SessionIdleTimeout = TimeSpan.FromSeconds(30);
     });
     b.AddTimers();
 });
```

Here is our code example:
```
public static async Task ProcessSQLCosmosDBEventExpansion([ServiceBusTrigger("queue", IsSessionsEnabled = true, Connection = ServiceBusConnection)] ServiceBusReceivedMessage message, ServiceBusMessageActions messageActions, ServiceBusSessionMessageActions sessionActions, CancellationToken cancellationToken)
 {
     try {
        var messageBody = Encoding.UTF8.GetString(message.Body);
        
        // handle the logic
        await messageActions.CompleteMessageAsync(message).ConfigureAwait(false);
        diagnostic.Success = true;
     }
     catch (Exception ex)
     {
         await messageActions.AbandonMessageAsync(message).ConfigureAwait(false);
         throw;
     }
     finally
     {
         try
         {
             // Release the session so the next message in the queue will be delivered.
             sessionActions.ReleaseSession();
         }
         catch (Exception ex)
         {
             telemetryClient.TrackException(ex, requestTelemetry.Properties);
         }

         telemetryClient.Flush();
     }
 }
```

Here is the exception stack trace:
```
System.ObjectDisposedException:
   at Azure.Core.Argument.AssertNotDisposed (Azure.Messaging.ServiceBus, Version=7.16.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver..ctor (Azure.Messaging.ServiceBus, Version=7.16.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at Azure.Messaging.ServiceBus.ServiceBusSessionReceiver+<CreateSessionReceiverAsync>d__7.MoveNext (Azure.Messaging.ServiceBus, Version=7.16.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Messaging.ServiceBus.SessionReceiverManager+<CreateReceiver>d__25.MoveNext (Azure.Messaging.ServiceBus, Version=7.16.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Messaging.ServiceBus.SessionReceiverManager+<CreateAndInitializeSessionReceiver>d__24.MoveNext (Azure.Messaging.ServiceBus, Version=7.16.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Messaging.ServiceBus.SessionReceiverManager+<EnsureCanProcess>d__22.MoveNext (Azure.Messaging.ServiceBus, Version=7.16.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Messaging.ServiceBus.SessionReceiverManager+<ReceiveAndProcessMessagesAsync>d__29.MoveNext (Azure.Messaging.ServiceBus, Version=7.16.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)

```

### Environment

.Net 6.0
Microsoft.Azure.WebJobs.Extensions 4.0.1
Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.8.0
Microsoft.Azure.WebJobs.Extensions.Storage 5.0.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
The only way I can see see how this could happen is if the ServiceBusListener.Dispose method was called without ServiceBusListener.StopAsync being called first, which is very unexpected behavior.

That said, this issue was [fixed](https://github.com/Azure/azure-sdk-for-net/commit/7e1e046960094ce147a4e8a51d0b3bb096ec0a23#diff-5a3cb066d3a354dc26c8f0cb29c6f4c2fa0478951efb964b02ae62ab4c07ae8fR309-R315) in 5.12.0, so upgrading should resolve the issue.

**Comment by ruoruyan** [comment]
Thank you all, I will try to upgrade to 5.12.0 first and update the result later.

**Comment by ruoruyan** [comment]
Hi @JoshLove-msft, I tried the upgrade version, but it doesn't seem to fix the problem, I still get this error.
![image](https://github.com/Azure/azure-sdk-for-net/assets/129138586/d952371f-87b2-41a3-84a9-07ed7379d6a2)
![image](https://github.com/Azure/azure-sdk-for-net/assets/129138586/aa3cd25b-38a1-4775-8468-2e311a0ca31a)

Call Stack:
System.ObjectDisposedException:
   at Azure.Core.Argument.AssertNotDisposed (Azure.Messaging.ServiceBus, Version=7.16.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver..ctor (Azure.Messaging.ServiceBus, Version=7.16.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at Azure.Messaging.ServiceBus.ServiceBusSessionReceiver+<CreateSessionReceiverAsync>d__7.MoveNext (Azure.Messaging.ServiceBus, Version=7.16.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Messaging.ServiceBus.SessionReceiverManager+<CreateReceiver>d__25.MoveNext (Azure.Messaging.ServiceBus, Version=7.16.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Messaging.ServiceBus.SessionReceiverManager+<CreateAndInitializeSessionReceiver>d__24.MoveNext (Azure.Messaging.ServiceBus, Version=7.16.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Messaging.ServiceBus.SessionReceiverManager+<EnsureCanProcess>d__22.MoveNext (Azure.Messaging.ServiceBus, Version=7.16.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Messaging.ServiceBus.SessionReceiverManager+<ReceiveAndProcessMessagesAsync>d__29.MoveNext (Azure.Messaging.ServiceBus, Version=7.16.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)

**Comment by JoshLove-msft** [comment]
Can you help us understand more about the lifecycle of the app? Do the errors occur after restarting the app? What does the shutdown/startup code look like? I suspect that the issue may be that we don't invalidate the cached clients [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Primitives/MessagingProvider.cs#L24), when the listener is being stopped, but I suspect this wouldn't be an issue for Functions users as the whole host process gets torn down.

**Comment by ruoruyan** [comment]
Hi @JoshLove-msft,

Here is our code:
```
var host = builder.Build();
using (host)
{
    var jobHost = host.Services.GetService(typeof(IJobHost)) as JobHost;

    ecsSettingsMonitor = host.Services.GetRequiredService<IOptionsMonitor<ExpansionECSConfig>>();

    await host.StartAsync(cancellationToken).ConfigureAwait(false);
    await jobHost.CallAsync(typeof(Expansion).GetMethod("KeepAlive"), cancellationToken).ConfigureAwait(false);
    await host.StopAsync(cancellationToken).ConfigureAwait(false);
}

/// <summary>
/// Keep Service Fabric app alive
/// </summary>
/// <param name="cancellationToken">cancellation token</param>
/// <returns>a task</returns>
[NoAutomaticTrigger]
public static async Task KeepAlive(CancellationToken cancellationToken)
{
    long iterations = 0;
    while (true)
    {
        cancellationToken.ThrowIfCancellationRequested();

        Trace.TraceInformation(string.Format(">>[{0}]ExpansionProcessMethod Working-{1}", DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss"), ++iterations));

        await Task.Delay(TimeSpan.FromSeconds(60), cancellationToken).ConfigureAwait(false);
    }
}
```

And the exception only occurs when we deploy our service (stop previous instance, and start a new one). Please let me know if you need more details. thanks

**Comment by ruoruyan** [comment]
I found something. We have four services with similar code, but one of them does not report this error. When I looked at the code, it was because we injected some configuration related to ECS. But I'm still not sure why these changes are causing this problem

 ```
builder.ConfigureLogging((context, b) =>
{
    b.AddConsole();
    b.AddApplicationInsights(configureTelemetryConfiguration: (config) => config.ConnectionString = telemetryConfig.ConnectionString, configureApplicationInsightsLoggerOptions: (options) => { });

    // Capture all log-level entries from Startup
    b.AddFilter<ApplicationInsightsLoggerProvider>("ExpansionStartup", LogLevel.Trace);
});
builder.ConfigureServices((hostingContext, services) => 
{
    services.AddEcs(options =>
    {
        options.ECSClientConfiguration.LoggerFactory = LoggerFactory.Create((action) => action.AddApplicationInsights(
                                    configureTelemetryConfiguration: (config) => config.ConnectionString = telemetryConfig.ConnectionString,
                                    configureApplicationInsightsLoggerOptions: (options) => { }));
        options.ECSClientConfiguration.ConfigureHttpMessageHandlers = builder => builder.AddHttpMessageHandler(() =>
            new EcsAuthHttpHandler(keyvaultReader, this.settings.GetConfig("ECSSettings", "ECSClientId"), this.settings.GetConfig("ECSSettings", "ECSCertName"), this.settings.GetConfig("ECSSettings", "ECSAuthority"), this.settings.GetConfig("ECSSettings", "ECSScope"), telemetryClient));
        options.ECSClientConfiguration.Environment = (Microsoft.Skype.ECS.Client.EnvironmentType)int.Parse(this.settings.GetConfig("ECSSettings", "ECSEnvType"));
        options.RequesterMode = RequesterMode.Local;
        options.ECSClientConfiguration.UseOfflineCache = true;
        options.ECSClientConfiguration.Cache = new ECSOfflineCacheBuilder()
                                                 .AddFileCache()
                                                 .AddAzureStorageCache(options =>
                                                 {
                                                     options.CloudStorageAccountConnectionString = keyvaultReader.GetSecret(this.parameters["SQLCosmosDBEventExpansionConnString"]?.Value).GetAwaiter().GetResult();
                                                     options.DefaultBlobContainerName = string.Format("expansion-ecs-cache-{0}", this.settings.GetConfig("ECSSettings", "ECSRegion"));
                                                 })
                                                .Build();
        options.ECSClientConfiguration.UseMtls = true;
        options.ECSClientConfiguration.ClientCertificate = keyvaultReader.GetCert(this.settings.GetConfig("ECSSettings", "ECSCertName")).ConfigureAwait(false).GetAwaiter().GetResult();
        options.ECSClientConfiguration.Client = "SubstrateModelD";
        options.ECSClientConfiguration.Agents = new[] { this.settings.GetConfig("ECSSettings", "ECSAgentName") };
        options.ECSClientConfiguration.DefaultRequestIdentifiers = new Dictionary<string, string> { { "EnvGroup", this.settings.GetConfig("ECSSettings", "ECSEnvGroup") }, { "Geo", this.settings.GetConfig("ECSSettings", "ECSRegion") } };
    });
    services.Configure<ExpansionECSConfig>(hostingContext.Configuration);
    services.AddEcsContextualOptions<ExpansionECSConfig>(string.Empty);
});
builder.ConfigureAppConfiguration((hostingContext, config) =>
{
    config.AddEcs(action =>
    {
        action.OnConfigurationError += (sender, args) => telemetryClient.TrackException(args.Exception);
        action.Configuration = new ECSClientConfiguration
        {
            LoggerFactory = LoggerFactory.Create((action) => action.AddApplicationInsights(
                                                        configureTelemetryConfiguration: (config) => config.ConnectionString = telemetryConfig.ConnectionString,
                                                        configureApplicationInsightsLoggerOptions: (options) => { })),
            ConfigureHttpMessageHandlers = builder => builder.AddHttpMessageHandler(() =>
            new EcsAuthHttpHandler(keyvaultReader, this.settings.GetConfig("ECSSettings", "ECSClientId"), this.settings.GetConfig("ECSSettings", "ECSCertName"), this.settings.GetConfig("ECSSettings", "ECSAuthority"), this.settings.GetConfig("ECSSettings", "ECSScope"), telemetryClient)),

            Environment = (Microsoft.Skype.ECS.Client.EnvironmentType)int.Parse(this.settings.GetConfig("ECSSettings", "ECSEnvType")),

            UseOfflineCache = true,
            Cache = new ECSOfflineCacheBuilder()
                .AddFileCache()
                .AddAzureStorageCache(options =>
                {
                    options.CloudStorageAccountConnectionString = keyvaultReader.GetSecret(this.parameters["SQLCosmosDBEventExpansionConnString"]?.Value).GetAwaiter().GetResult();
                    options.DefaultBlobContainerName = string.Format("expansion-ecs-cache-{0}", this.settings.GetConfig("ECSSettings", "ECSRegion"));
                })
                .Build(),

            UseMtls = true,
            ClientCertificate = keyvaultReader.GetCert(this.settings.GetConfig("ECSSettings", "ECSCertName")).ConfigureAwait(false).GetAwaiter().GetResult(),
            Client = "SubstrateModelD",
            Agents = new[] { this.settings.GetConfig("ECSSettings", "ECSAgentName") },
            DefaultRequestIdentifiers = new Dictionary<string, string>
            {
                { "EnvGroup", this.settings.GetConfig("ECSSettings", "ECSEnvGroup") },
                { "Geo", this.settings.GetConfig("ECSSettings", "ECSRegion") }
            },
        };
    });
});
```

**Comment by JoshLove-msft** [comment]
I'm not familiar with "ECS" nor can I see why the code above should result in the behavior you are seeing. Are you able to include a minimal repro that I can run locally?

**Comment by ruoruyan** [comment]
Thanks @JoshLove-msft, since the ECS changes was not made by me, I will sync with others to see if I can provide a minimal repro that you can run locally later.

**Comment by JoshLove-msft** [comment]
One other question - do you have multiple functions in your app or just one?

**Comment by ruoruyan** [comment]
Hi @JoshLove-msft, we have one function for the queue and another one for the deadletter queue, not sure if that counts as multiple methods. And we don't register a MessagingProvider manually.

**Comment by JoshLove-msft** [comment]
> Hi @JoshLove-msft, we have one function for the queue and another one for the deadletter queue, not sure if that counts as multiple methods. And we don't register a MessagingProvider manually.

Thanks, while investigating the code, the only way I could see this issue happening was if a MessagingProvider instance was shared between Host instances, which would only be the case if you were intentionally doing this. At this point I'm just waiting for a repro so I can debug further.
