### ISSUE TITLE
Is Azure.Maps.Search 1.0.0-beta.5 no longer available?

### ISSUE THREAD

**Issue by MikeMSTG** [Azure/azure-sdk-for-net#45421]
### Library name and version

Azure.Maps.Search 1.0.0-beta.5

### Query/Question

Is Azure.Maps.Search 1.0.0-beta.5 no longer available?

### Environment

.NET Framework 4.8 application; compiling under VS 2022 Version 17.10.5.

**Comment by MikeMSTG** [comment]
I should note I am receiving the following: Unhandled Exception: Retry failed after 4 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a custom retry policy in ClientOptions.RetryPolicy.

**Comment by dubiety** [comment]
Hi @MikeMSTG , 

I don't see any problem when downloading or building .NET framework4.8 application from my side. Can you try to run the command in the project folder and see if it successfully shows in your *.csproj file?
```powershell
cd to\your\csproj\directory
dotnet add package Azure.Maps.Search -v 1.0.0-beta.5
```

Also, we just released our latest [Azure.Maps.Search v2.0.0-beta.1](https://www.nuget.org/packages/Azure.Maps.Search/2.0.0-beta.1) which maps to our latest [Search API version 2023-06-01](https://learn.microsoft.com/en-us/rest/api/maps/search?view=rest-maps-2024-04-01) that you can also give it a try. Let me know if you still encounter the problem.

**Comment by MikeMSTG** [comment]
> Hi @MikeMSTG ,
> 
> I don't see any problem when downloading or building .NET framework4.8 application from my side. Can you try to run the command in the project folder and see if it successfully shows in your *.csproj file?
> 
> ```powershell
> cd to\your\csproj\directory
> dotnet add package Azure.Maps.Search -v 1.0.0-beta.5
> ```
> 
> Also, we just released our latest [Azure.Maps.Search v2.0.0-beta.1](https://www.nuget.org/packages/Azure.Maps.Search/2.0.0-beta.1) which maps to our latest [Search API version 2023-06-01](https://learn.microsoft.com/en-us/rest/api/maps/search?view=rest-maps-2024-04-01) that you can also give it a try. Let me know if you still encounter the problem.

I should have been more specific.  I was asking if the beta 5 was still available _on the server side_, which is to say when I run my code (which still is available on nuget), the beta 5 logic no longer works against server requests.

**Comment by MikeMSTG** [comment]
Any update as to why the Search call is producing an error?

**Comment by dubiety** [comment]
Hi @MikeMSTG ,

Sorry for the late reply. We've found the issue for v2.0.0 beta.1 and fix the bug you mentioned in v2.0.0 beta.2. Please download it on [NuGet Azure.Maps.Search](https://www.nuget.org/packages/Azure.Maps.Search).

As of v1.0.0 beta.5, it's still available on server side. I've tried to use v1.0.0 beta.5 without any problem. If possible, can you share the code snippet you used? Thank you so much.

**Comment by MikeMSTG** [comment]
I updated to 2.0 beta 2 and I am still experiencing the same error.  

`
Dim _azureKeyCredential As New AzureKeyCredential(ConfigurationManager.AppSettings("AzureMapKey"))
Dim searchClient As New MapsSearchClient(_azureKeyCredential)
Dim batchOperation As Response(Of GeocodingBatchResponse) = searchClient.GetGeocodingBatch(addressesToSearch)
`

Produces: Retry failed after 4 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a custom retry policy in ClientOptions.RetryPolicy.

**Comment by MikeMSTG** [comment]
United States.

**Comment by MikeMSTG** [comment]
@dubiety - I decided to create a separate app using .NET 8 and the beta 2 is functional.  

Is there an issue using the .NET Framework 4.8 as it was literally the same code but only one works.

**Comment by MikeMSTG** [comment]
any update?

**Comment by dubiety** [comment]
Hi @MikeMSTG ,

I'm ok with Framework version 4.8 application. The code I test:

```vb
Imports Azure
Imports Azure.Maps.Search
Imports Azure.Maps.Search.Models
Imports Azure.Maps.Search.Models.Queries

Module Module1

    Sub Main()
        Dim addressesToSearch As New List(Of GeocodingQuery)()
        Dim queryEntry As New GeocodingQuery()
        With queryEntry
            .Query = "123 1st St., Dallas, TX 75007"
        End With

        addressesToSearch.Add(queryEntry)

        Dim _azureKeyCredential As New AzureKeyCredential(ConfigurationManager.AppSettings("AzureMapKey"))
        Dim searchClient As New MapsSearchClient(_azureKeyCredential)
        Dim batchOperation As Response(Of GeocodingBatchResponse) = searchClient.GetGeocodingBatch(addressesToSearch)
        For Each item As GeocodingBatchResponseItem In batchOperation.Value.BatchItems
            Debug.Print(item.Features.FirstOrDefault().Geometry.Coordinates(0).ToString())
            Debug.Print(item.Features.FirstOrDefault().Geometry.Coordinates(1).ToString())
        Next
    End Sub

End Module
```

**Comment by MikeMSTG** [comment]
I'm not sure why I continue to receive the error message I posted previously. I'm going to change approaches and have an API instead since it appears my .NET framework code does not work.

**Comment by dubiety** [comment]
OK. I'll close this bug, but please open anytime if you think there's anything else I can help. Thank you for the understand.
