### ISSUE TITLE
[FEATURE REQ] Implement stored access policies for the V12 storage API. 

### ISSUE THREAD

**Issue by PhilStollery** [Azure/azure-sdk-for-net#9549]
**Is your feature request related to a problem? Please describe.**
The new storage API doesn't implement stored access policies for SAS. It needs to be included so we can stop using V11 of the storage API. 

**Describe the solution you'd like**
Implement stored access policies and add examples into Sample02_Auth.cs. 

**Describe alternatives you've considered**
Alternative are I have to fall back to V11 of the storage API. 

**Additional context**
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-dotnet
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-dotnet-legacy

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by tg-msft** [comment]
I believe this was already fixed this with https://github.com/Azure/azure-sdk-for-net/pull/9441.  Can you confirm @seanmcc-msft?

**Comment by PhilStollery** [comment]
I think the API supports it, but there's no example of how to do it in Sample02_Auth.cs

**Comment by amishra-dev** [comment]
The customer is looking for a sample update.

**Comment by amnguye** [comment]
I agree, after we made our recent changes to fix this we didn't create any samples to show users how to use it. We will look to update the samples Blobs to implement stored access policies for SAS.

**Comment by gurufordy** [comment]
Hi, I just ran into an issue where a SAS Token created against a container works in the new API, but creating a SAS Token against a policy which is against a container doesn't work (403).

Does that mean that this feature is still not working or is it something else?

Thanks.

**Comment by amnguye** [comment]
Hi @gurufordy, could you make a new issue with what you're attempting to do the creation of your SAS token and what you're trying to achieve? When you say a policy, do you mean a container that already has a Access Policy applied to it? Also a code snippet would be very helpful as well. Thanks!

**Comment by gurufordy** [comment]
Hi @amnguye,

Thanks for getting back to me so quickly! Below is what I was running, where the policy and SAS creation go fine:

```
az storage container policy create --name $PolicyName -c $ContainerName --account-name $StorageResourceName --start $sasStartDate --expiry $sasEndDate --permissions $Permissions
$sasToken = az storage container generate-sas --name $ContainerName --account-name $StorageResourceName --policy-name $PolicyName
$sasUri = "https://$StorageResourceName.blob.core.windows.net/$($ContainerName)?$sasToken"
```

And then using in DNC with Azure.Storage.Blobs Nuget package:

```
string blobSasUri = Encryption.DecryptAes(ConfigurationManager.AppSettings["BlobSasTokenUri"]);
var blobServiceClient = new BlobServiceClient(new Uri(blobSasUri));
BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient("mysubfolder");
containerClient.CreateIfNotExistsAsync();
return containerClient;
```

The client created then can't upload a new blob into the container and gives a 403 HTTP code. Doing the same thing by hand yields the same rejection. Doing the same thing with no policy works fine. 

Any ideas?

**Comment by amnguye** [comment]
@gurufordy Could you make a new issue with this information and the other information that is asked in the form? Thanks

**Comment by WillRock19** [comment]
I've ran into the same problem. Trying to implement stored access policies to make something but it does not work. I'm currently using the **Microsoft.WindowsAzure.Storage.Blobs version 9.3.2.0** and trying to update it to Azure.Storage.Blobs.

The code I'm trying to migrate is as follows:

```csharp
        private void ClearAndCreateStoredAccessPolicy(CloudBlobContainer container)
        {
            SharedAccessBlobPolicy sharedPolicy = new SharedAccessBlobPolicy()
              {
                  Permissions = SharedAccessBlobPermissions.Read,
              };

            var permissions = container.GetPermissions();
            permissions.SharedAccessPolicies.Clear();
            permissions.SharedAccessPolicies.Add(policy.ToString(), sharedPolicy);
            container.SetPermissions(permissions);
        }
```

There are any updates in this matter? Do you guys can put in the sample an Example of how to do this?

**Comment by JimSuplizio** [comment]
Hi @PhilStollery, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
